# ============================================================
# THEME DEFINITIONS
# ============================================================
# Each theme is a dictionary of color names used throughout the UI.
# To create a new theme, just copy one and change the color values.
# Colors can be any Rich color: https://rich.readthedocs.io/en/latest/appendix/colors.html

THEMES = {
    "ocean": {
        "name": "Ocean",
        "description": "Cool, calm - cyan & blue tones",
        "primary": "cyan",
        "secondary": "blue",
        "accent": "bright_cyan",
        "success": "green",
        "warning": "yellow",
        "error": "red",
        "muted": "dim",
        "user_prompt": "bold cyan",
        "toolbar_bg": "#1a3a4a",
        "toolbar_fg": "#88ccdd",
    },
    "sunset": {
        "name": "Sunset",
        "description": "Warm, bold - orange & red tones",
        "primary": "dark_orange",
        "secondary": "yellow",
        "accent": "bright_red",
        "success": "green",
        "warning": "yellow",
        "error": "red",
        "muted": "dim",
        "user_prompt": "bold #ff8c00",
        "toolbar_bg": "#4a2a1a",
        "toolbar_fg": "#ddaa88",
    },
    "forest": {
        "name": "Forest",
        "description": "Natural, earthy - green tones",
        "primary": "green",
        "secondary": "dark_green",
        "accent": "bright_green",
        "success": "bright_green",
        "warning": "yellow",
        "error": "red",
        "muted": "dim",
        "user_prompt": "bold green",
        "toolbar_bg": "#1a3a1a",
        "toolbar_fg": "#88dd88",
    },
    "neon": {
        "name": "Neon",
        "description": "Cyberpunk, bright - magenta & pink",
        "primary": "magenta",
        "secondary": "bright_magenta",
        "accent": "bright_cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "muted": "dim",
        "user_prompt": "bold magenta",
        "toolbar_bg": "#2a1a3a",
        "toolbar_fg": "#dd88ff",
    },
    "monochrome": {
        "name": "Monochrome",
        "description": "Clean, minimal - white & gray only",
        "primary": "white",
        "secondary": "bright_white",
        "accent": "white",
        "success": "bright_white",
        "warning": "white",
        "error": "bright_white",
        "muted": "dim",
        "user_prompt": "bold white",
        "toolbar_bg": "#333333",
        "toolbar_fg": "#aaaaaa",
    },
    "dracula": {
        "name": "Dracula",
        "description": "Classic dark theme - purple & pink",
        "primary": "medium_purple3",
        "secondary": "hot_pink",
        "accent": "bright_cyan",
        "success": "bright_green",
        "warning": "bright_yellow",
        "error": "bright_red",
        "muted": "dim",
        "user_prompt": "bold #af5fff",
        "toolbar_bg": "#282a36",
        "toolbar_fg": "#bd93f9",
    },
}
